Try to fix crashes on strange devices.
I am seeing a lot of this error in production. Maybe this will fix it.

org.xmlpull.v1.XmlPullParserException: Binary XML file line #18: <item> tag requires a 'drawable' attribute or child tag defining a drawable